name: Wander

packages:
  Parchment:
    url: https://github.com/rechsteiner/Parchment
    from: "4.0.0"
  SwiftyH3:
    url: https://github.com/pawelmajcher/SwiftyH3.git
    minorVersion: "0.5.0"
  DBSCAN:
    url: https://github.com/NSHipster/DBSCAN
    from: "0.0.1"

options:
  bundleIdPrefix: com.zerolive
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  groupSortPosition: top
  defaultConfig: Debug
  developmentLanguage: ko
  localizedStringSwiftUISupport: true

schemes:
  Wander:
    build:
      targets:
        Wander: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

settings:
  base:
    SWIFT_VERSION: "5.9"
    DEVELOPMENT_TEAM: "XU8HS9JUTS"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    INFOPLIST_KEY_CFBundleDisplayName: "Wander"
    INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.travel"
    SWIFT_EMIT_LOC_STRINGS: "YES"
    ASSETCATALOG_COMPILER_APPICON_NAME: "AppIcon"
    ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: "AccentColor"

targets:
  Wander:
    type: application
    platform: iOS
    supportedDestinations: [iOS]
    dependencies:
      - package: Parchment
      - package: SwiftyH3
      - package: DBSCAN
    sources:
      - WanderApp.swift
      - ContentView.swift
      - Core
      - Models
      - Services
      - ViewModels
      - Views
      - Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.zerolive.wander
        SDKROOT: iphoneos
        TARGETED_DEVICE_FAMILY: "1,2"
        GENERATE_INFOPLIST_FILE: NO
        INFOPLIST_FILE: Info.plist
        CODE_SIGN_ENTITLEMENTS: Wander.entitlements
